name: Debug GitHub Branch List

on:
  workflow_dispatch:
  push:


permissions:
  contents: read


jobs:

  debug:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v5


      - name: Check repositories

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |

          echo "Repositories:"

          gh api \
            /users/CodeByMaxx/repos \
            --paginate \
            --jq '.[].name'


      - name: Check branches

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |

          echo "Branches:"

          for repo in $(gh api /users/CodeByMaxx/repos --paginate --jq '.[].name')
          do

            echo "===================="
            echo "Repository: $repo"

            gh api \
              /repos/CodeByMaxx/$repo/branches \
              --jq '.[].name'

          done
