name: Update GitHub Branch List

on:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:


permissions:
  contents: write


jobs:

  update-branches:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v5


      - name: Generate branches.json

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |

          mkdir -p assets


          echo "[" > assets/branches.json

          FIRST=true


          gh api \
            --paginate \
            /users/CodeByMaxx/repos \
            --jq '.[].name' |
          while read repo
          do

            echo "Checking repository: $repo"


            has_topic=$(gh api \
              /repos/CodeByMaxx/$repo/topics \
              --jq '.names | index("portfolio")')


            if [ "$has_topic" != "null" ]
            then

              echo "Portfolio repository found: $repo"


              branches=$(gh api \
                /repos/CodeByMaxx/$repo/branches \
                --jq '
                .[].name |
                select(
                  . != "main" and
                  . != "master" and
                  . != "develop"
                )
                ')


              if [ -n "$branches" ]
              then


                if [ "$FIRST" = false ]
                then
                  echo "," >> assets/branches.json
                fi


                FIRST=false


                echo "{" >> assets/branches.json

                echo "\"repository\":\"$repo\"," >> assets/branches.json

                echo "\"branches\":[" >> assets/branches.json


                echo "$branches" |
                awk '
                BEGIN {first=1}
                {
                  if (!first) printf ","
                  printf "\"%s\"", $0
                  first=0
                }
                ' >> assets/branches.json


                echo "]}" >> assets/branches.json

              fi

            fi

          done


          echo "]" >> assets/branches.json



      - name: Show result

        run: cat assets/branches.json



      - name: Commit changes

        run: |

          git config user.name "github-actions"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"


          git add assets/branches.json


          git diff --cached --quiet || \
          git commit -m "Update portfolio branches"


          git push
